### ISSUE TITLE
Merge to pygments-main?

### ISSUE THREAD

**Issue by birkenfeld** [Tuurlijk/Pygments-TypoScript-Lexer#1]
Merging this lexer is requested in https://bitbucket.org/birkenfeld/pygments-main/issues/1173

Before doing that, I'ld like to get your OK for the contribution. Thanks!

**Comment by marble** [comment]
Hi Michiel, oh yes please, give Georg Brandl the "Ok!". I think I tried to get our TypoScript lexer in before already but for some reason it got out of sight. Looking forward to it: Saves the TYPO3 community quite a bit of a hassle.

**Comment by Tuurlijk** [comment]
OK! ;-)

**Comment by birkenfeld** [comment]
Done!

**Comment by Tuurlijk** [comment]
\o/

**Comment by Chrissitopher** [comment]
Hi Michiel, thanks for writing this lexer and for allowing Georg to merge it.
Georg, thanks for integrating it!

Since MediaWiki version 1.26 TypoScript highlighting had been missing in MediaWiki. With this patch in, TypoScript highlighting will also be available again in future versions of MediaWiki. That is great! :-)
